CREATE TABLE accounts (
	id UUID PRIMARY KEY DEFAULT uuidv7(),
	email TEXT NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
